kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/dwin/goArgonPass

steps:
  - name: build-alpine-latest
    image: golang:alpine
    pull: always
    commands:
      - go build -race -v .

  - name: test-1.11-alpine
    image: golang:1.11-alpine
    commands:
      - apk add --update bash build-base
      - go test ./...

  - name: test-1.12-alpine
    image: golang:1.12-alpine3.9
    commands:
      - apk add --update bash build-base
      - go test ./...

  - name: test-alpine_latest
    image: golang:alpine
    pull: always
    commands:
      - apk add --update bash build-base
      - go test -coverprofile=coverage.txt -covermode=atomic ./...
      - bash <(curl -s https://codecov.io/bash)
  # - name: coverage
  #   image: plugins/codecov
  #   settings:
  #     required: true
  #     token:
  #       from_secret: codecov_token
  #     files:
  #       - coverage.txt
